# 应用服务 WEB 访问端口
server.port=8080
servlet:
context-path: /api  # ???baseUrl??

spring:
datasource:
driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://localhost:3306/stuclubmanagement?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
username: root  # ?????MySQL??
password: 12345
multipart:
max-file-size: 5MB  # ????????
max-request-size: 10MB

# MyBatis-Plus??
mybatis-plus:
configuration:
map-underscore-to-camel-case: true 
log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ??SQL
mapper-locations: classpath:mapper/**/*.xml
type-aliases-package: com.manage.club.entity

# JWT??
jwt:
secret: clubManage202406  # ?????16??
expire: 86400000  # Token???1?????

# ??????
upload:
base-path: ./uploads/  # ??????
access-path: /uploads/**  # ??????
